### ISSUE TITLE
Is this a free plugin?

### ISSUE THREAD

**Issue by htorbov** [rahadur/capacitor-admob#30]
Hi! Is this 100% free plugin, without any monetisation-share techniques? Also, there's a bug in the Android bottom banner ads - the ad is appearing on the left instead on the center (it's OK in the iOS). Thanks!

**Comment by rahadur** [comment]
@htorbov This is a 100% free plugins.  it has no monetisation-share techniques. 

**Bug Report:**
Did you use `AdSize = "SMART_BANNER"` option? and `AdPosition = "CENTER"`

If you use this params on banner ad. please share your Device & Android OS details. So that i can  re generate this issue on my side.

Thank you for your report.
