### ISSUE TITLE
Admob Native Ads support?

### ISSUE THREAD

**Issue by Scottd125** [rahadur/capacitor-admob#31]
Hello, I would like to know if you have any plans to add Admob Native Ads support with this plugin or if there are some limitations that prevent Admob Native Ads from being implemented with this plugin or with capacitor in general. Keep up the great work!

**Comment by rahadur** [comment]
hello @Scottd125 i am also interested  to implement AdMob Native Ad support! Unfortunately, i did not found any proper solution. because in Ionic we are working with **Web Component** it's not a Native Components Such as `ion-list`,  `ion-content` that's why we can't directly access  our web components from Native code. i will have to find a properly solution. If is's possible i will defiantly implement this.

Thank you.

**Comment by Scottd125** [comment]
Hey rahadur, thanks for the quick response! It's a shame since I would have hoped that capacitor could have potentially resolved this issue with being able to create a custom plugin to run native code and being able to hook the data (Ad) returned from Admob, up with the DOM instead of a native view but I can imagine it's much more complicated than that with a whole lot of factors. Thank you for your reply and letting me know you will get it implemented if you manage to find a possible solution :)
