### ISSUE TITLE
Admob Id clarification?

### ISSUE THREAD

**Issue by prantikv** [rahadur/capacitor-admob#5]
hey there,

As mentioned in the readme file we need to add the following in the **AndroidManifest.xml**

`  <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3940256099942544~3347511713" />`

Note here that the Ad id has a "~" (tilde) symbol. 

While the ad id that we get from AdMob have a "/" (slash) for ex  `ca-app-pub-3940256099942544/6300978111`

So which format is the ad id supposed to be enterned?

Also, we are entering the AdMob Id in the **AndroidManifest.xml** and we are also supposed to the Id while coding the class as shown below.

```
export class AdMobComponent {

    const options: AdOptions = {
        adId: 'YOUR ADID',
        adSize: AdSize.Banner,
        position: AdPosition.BOTTOM_CENTER
    }
```
Which Admob Id will take precedence? 
Why do we need to add it two times?
What happens if we have to use two Id, ex. for banner and interstitials. How to we code the **AndroidManifest.xml** then?

Need some clarification on this.

Thanks

**Comment by rahadur** [comment]
* Which Admob Id will take precedence?
* Why do we need to add it two times?

in document [here](https://github.com/rahadur/capacitor-admob#-update-manifest) i mention that in **AndroidManifest.xml** you have to add **APP ID** not **AD Unit ID**

[Watch This Video for understand difference between APP ID & AD Unit ID](https://www.youtube.com/watch?v=BHLeAMcykOI)  

```xml
<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID"
 android:value="ca-app-pub-3940256099942544~3347511713" />
```

* What happens if we have to use two Id, ex. for banner and interstitials. How to we code the AndroidManifest.xml then?

For work with different banner style you have to create different **AD Unit ID** from your AdMob Account. after that you can show your **AD** by using `capacitor-admob` plugins. In this plugins i have implement different methods to show different types of AD. You don't have to anything else once you add your **APP ID** in **AndroidManifest.xml** file.

Please read Google [AdMob Quick Start Guid ](https://developers.google.com/admob/android/quick-start) for batter understanding.
